  server:
    port: 8081
  spring:
    application:
      name: fraud
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/fraud
      username: habscode
      password: password
    jpa:
      hibernate:
        ddl-auto: create-drop
        jdbc:
          time-zone: UTC
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    zipkin:
      base-url: http://localhost:9411

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
      enabled: false